# Generated by Django 5.0.2 on 2024-04-11 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FiltroCapacidadManual',
            fields=[
                ('ID_ATT', models.TextField(max_length=50, primary_key=True, serialize=False)),
                ('TX', models.TextField(max_length=50)),
                ('TX_GRUPOS_MANUAL', models.TextField(max_length=50)),
                ('TX_DETALLE_MANUAL', models.TextField(max_length=50)),
                ('FECHA', models.TextField(max_length=50)),
                ('POC', models.TextField(max_length=50)),
                ('OBSERVACIONES', models.TextField(max_length=50)),
                ('TRACKER', models.TextField(max_length=50)),
                ('ATT_ID', models.TextField(max_length=50)),
                ('NOMBRE', models.TextField(max_length=50)),
                ('LATITUD', models.TextField(max_length=50)),
                ('LONGITUD', models.TextField(max_length=50)),
                ('ESTADO', models.TextField(max_length=50)),
                ('MUNICIPIO', models.TextField(max_length=50)),
                ('MERCADO', models.TextField(max_length=50)),
                ('REGION_CELULAR', models.TextField(max_length=50)),
                ('REGION', models.TextField(max_length=50)),
                ('VENDOR', models.TextField(max_length=50)),
                ('COBERTURA', models.TextField(max_length=50)),
                ('TIPO', models.TextField(max_length=50)),
                ('PROYECTO', models.TextField(max_length=50)),
                ('CLASIFICACION', models.TextField(max_length=50)),
                ('CONTROL_CAMBIOS_RAN', models.TextField(max_length=50)),
                ('BASE_ORIGEN_TX', models.TextField(max_length=50)),
                ('GRUPOS_MEDIO_TX', models.TextField(max_length=50)),
                ('TX_DETALLE', models.TextField(max_length=50)),
                ('CAPACIDAD', models.TextField(max_length=50)),
                ('CONTROL', models.TextField(max_length=50)),
            ],
            options={
                'db_table': 'tb1_capacidadManual',
            },
        ),
    ]
